MusicBoard/ViewModels/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MusicBoard.ViewModels
{

    public class LoginViewModel
    {
        [Required(ErrorMessage = "Не указан логин")]
        public String Login { get; set; }

        [Required(ErrorMessage = "Не указан пароль")]
        [DataType(DataType.Password)]
        public String Password { get; set; }
    }

}

MusicBoard/ViewModels/RatingsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MusicBoard.ViewModels
{
    public class RatingsViewModel
    {
        public IEnumerable<AlbumRatingViewModel> Ratings { get; set; }
        public PageViewModel PageViewModel { get; set; }
        public UserAnchorViewModel UserAnchor { get; set; }
        public Int32 RatingConstraint { get; set; }
    }
}

MusicBoard/ViewModels/UserInfoViewModel.cs
using MusicBoard.Models;
using MusicBoard.Services;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using static MusicBoard.Controllers.ArtistController;

namespace MusicBoard.ViewModels
{
    public class UserInfoViewModel
    {
        public Int32 SurrogateId { get; set;  }

        public DateTime RegistrationDate { get; set; }

        [Required(ErrorMessage = "Укажите никнейм")]
        [MaxLength(50, ErrorMessage = "Никнейм должен занимать меньше 50 строк")]
        [RegularExpression(@"^[a-z0-9_]+$", ErrorMessage = "url-адрес модет содержать только строчные английские символы, цифры и знак '_'")]
        public String Nickname { get; set; }

        [Required(ErrorMessage = "Укажите E-mail")]
        [EmailAddress(ErrorMessage = "Некорректный Email")]
        [MaxLength(100, ErrorMessage ="Длина Email-адреса не должна превышать 100 символов")]
        public String Email { get; set; }

        [Required(ErrorMessage = "Введите пароль")]
        [DataType(DataType.Password)]
        [StringLength(20, MinimumLength = 6, ErrorMessage ="Допустимая длина пароля: от 6 до 20 символов")]
        public String Password { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Compare("Password", ErrorMessage = "Пароль введен неверно")]
        public String ConfirmPassword { get; set; }

        [MaxLength(50, ErrorMessage ="Имя не может превышать 50 символов")]
        public String Name { get; set; }
        [MaxLength(50, ErrorMessage ="Фамилия не может превышать 50 символов")]
        public String Surname { get; set; }

        [DataType(DataType.Date)]
        public DateTime? BirthDate { get; set; }

        [MaxLength(50, ErrorMessage = "Наименование страны может быть сокращено до 50 символов?")]
        public String Country { get; set; }

        public Gender Gender { get; set; }

        [MaxLength(10000, ErrorMessage = "Длина текста не должна превышать 10000 символов")]
        public String About { get; set; }

        [MaxLength(5000, ErrorMessage = "Длина текста не должна превышать 5000 символов")]
        public String Favourites { get; set; }
        
        public Boolean HasImage { get; set; } = false;

        public List<AlbumRatingViewModel> Ratings { get; set; } = new List<AlbumRatingViewModel>();
        public Int32 RatingsCount { get; set; }

        public String[] FavouritesLexems { get; set; }
        public ArtistAnchorDTO[] FavouritesAnchors { get; set; }
    }
}

MusicBoard/Controllers/UserProfileController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using MusicBoard.Models;
using MusicBoard.Services;
using MusicBoard.ViewModels;
using Newtonsoft.Json.Linq;

namespace MusicBoard.Controllers
{
    public class UserProfileController : Controller
    {
        private static Random m_rand = new Random();
        private MusicBoardDbContext m_db;

        public UserProfileController(MusicBoardDbContext context)
        {
            m_db = context;
        }

        [HttpGet]
        [Route("@{nickname}")]
        public async Task<IActionResult> UserInfo([FromRoute] String nickname)
        {
            if (!m_db.Users.Any()) return NotFound();

            var o = await m_db.Users
                .Where(u => u.Login == nickname)
                .Select(user => new
                {
                    vm = new UserInfoViewModel
                    {
                        SurrogateId = user.UserId,
                        RegistrationDate = user.RegistrationDate,
                        Nickname = user.Login,
                        Name = user.Name,
                        Surname = user.Surname,
                        Country = user.Country,
                        Gender = user.Gender,
                        About = user.About,
                        HasImage = user.HasImage,
                        BirthDate = user.BirthDate,
                        RatingsCount = user.Ratings.Count,
                        Ratings = user.Ratings
                            .OrderByDescending(r => r.Date)
                            .Take(5)
                            .Select(r => new AlbumRatingViewModel(
                                r.Album.AlbumUrlName,
                                r.Album.AlbumFullName,
                                r.Album.ReleaseDate.Year,
                                r.Album.AlbumType,
                                new ArtistAnchorViewModel(r.Album.Artist.ArtistUrlName, r.Album.Artist.ArtistFullName))
                                {
                                    AlbumId = r.AlbumId,
                                    HasImage = r.Album.HasImage,
                                    Rating = r.Value,
                                    RatingDate = r.Date,
                                    Genres = r.Album.Genres.Select(g => new GenreAnchorViewModel(g.GenreId, g.Genre.GenreName)).ToArray()
                                })
                            .ToList()
                    },
                    artistsData = user.FavouriteArtistsData
                })
                .FirstOrDefaultAsync();

            if (o == null || o.vm == null) return NotFound();

            JToken lexems = null, anchors = null;
            o.artistsData?.TryGetValue("lexems", out lexems);
            o.artistsData?.TryGetValue("anchors", out anchors);

            o.vm.FavouritesLexems = lexems?.ToObject<String[]>();
            o.vm.FavouritesAnchors = anchors?.ToObject<ArtistAnchorDTO[]>();

            return View(o.vm);
        }

        [Route("@{nickname}/[action]")]
        public async Task<IActionResult> Ratings(String nickname, [FromQuery] Int32 rating = 0, [FromQuery]Int32 page = 1)
        {
            Int32 pageSize = 50;

            var vm = await m_db.Users.Where(u => u.Login == nickname)
                .Select(u => new RatingsViewModel
                {
                    Ratings = u.Ratings
                        .Where(r => rating == 0 || r.Value == rating)
                        .OrderByDescending(r => r.Date)
                        .Skip((page - 1) * pageSize)
                        .Take(pageSize)
                        .Select(r => new AlbumRatingViewModel(
                            r.Album.AlbumUrlName,
                            r.Album.AlbumFullName,
                            r.Album.ReleaseDate.Year,
                            r.Album.AlbumType,
                            new ArtistAnchorViewModel(r.Album.Artist.ArtistUrlName, r.Album.Artist.ArtistFullName))
                        {
                            AlbumId = r.AlbumId,
                            HasImage = r.Album.HasImage,
                            Rating = r.Value,
                            RatingDate = r.Date,
                            Genres = r.Album.Genres.Select(g => new GenreAnchorViewModel(g.GenreId, g.Genre.GenreName)).ToArray()
                        }).ToList(),
                    PageViewModel = new PageViewModel(u.Ratings.Count, page, pageSize),
                    UserAnchor = new UserAnchorViewModel(u.Login, u.UserId, null),
                    RatingConstraint = rating
                }
                ).FirstOrDefaultAsync();

            if (vm == null) return NotFound();

            return View(vm);
        }


        [HttpGet]
        [Route("[action]")]
        public IActionResult Registration()
        {
            if (User.Identity.IsAuthenticated)
                return StatusCode(StatusCodes.Status403Forbidden);
            return View();
        }

        [HttpPost]
        [Route("[action]")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Registration([FromForm]UserInfoViewModel model, [FromServices] ArtistRelationsMarkupParser parser)
        {
            if (!ModelState.IsValid) return View(model);

            if (await m_db.Users.AnyAsync(u => u.Login == model.Nickname))
            {
                ModelState.AddModelError("Nickname", "Пользователь с таким ником уже существует");
            }

            if (model.BirthDate > DateTime.Now)
            {
                ModelState.AddModelError("BirthDate", "Указана неверная дата рождения");
            }

            String[] favourites = null;
            ArtistAnchorDTO[] favouritesAnchors = null;

            try
            {
                (favourites, favouritesAnchors) = parser.ParseBands(model.Favourites);
            }
            catch (ArgumentException e)
            {
                ModelState.AddModelError("FavouriteMusicians", e.Message);
            }

            if (ModelState.IsValid)
            {
                User user = new User
                {
                    Login = model.Nickname,
                    Password = model.Password,
                    Email = model.Email,
                    Name = model.Name,
                    Surname = model.Surname,
                    Country = model.Country,
                    Gender = model.Gender,
                    About = model.About,
                    BirthDate = model.BirthDate,
                    RegistrationDate = DateTime.Now,

                    FavouriteArtistsData = JObject.FromObject(new { lexems = favourites, anchors = favouritesAnchors })
                };

                await m_db.Users.AddAsync(user);
                await m_db.SaveChangesAsync();

                await Authenticate(user.Login);

                return RedirectToAction("UserInfo", new { nickname = user.Login });
            }
            else return View(model);
        }

        [Route("[action]")]
        public IActionResult Login()
        {
            if (User.Identity.IsAuthenticated)
                return StatusCode(StatusCodes.Status403Forbidden);
            return View();
        }

        [HttpPost]
        [Route("[action]")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(LoginViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = await m_db.Users.FirstOrDefaultAsync(u => u.Login == model.Login && u.Password == model.Password);
                if (user != null)
                {
                    await Authenticate(model.Login); // аутентификация

                    return RedirectToAction("UserInfo", new { nickname = model.Login });
                }
                ModelState.AddModelError("", "Некорректные логин и(или) пароль");
            }
            return View(model);
        }

        [Authorize]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Login");
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> SetImage(IFormFile image, [FromServices] IHostingEnvironment env)
        {
            string nickname = User?.Identity?.Name;
            if (nickname == null) return Forbid();

            if (image != null)
            {
                var user = await m_db.Users.FirstAsync(a => a.Login == nickname);

                String path = env.WebRootPath + "/images/users/" + user.UserId + ".jpg";
                using (var stream = new FileStream(path, FileMode.Create))
                {
                    await image.CopyToAsync(stream);
                }

                
                user.HasImage = true;

                await m_db.SaveChangesAsync();

                return RedirectToAction("UserInfo", new { nickname = user.Login });
            }

            return StatusCode(StatusCodes.Status204NoContent);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> SetRating(Int32 albumId, Int32 rating)
        {
            String username = User?.Identity?.Name;

            if (username != null)
            {
                var album = await m_db.Albums.FirstOrDefaultAsync(a => a.Id == albumId);
                var userId = await m_db.Users.Where(u => u.Login == username).Select(u => u.UserId).FirstOrDefaultAsync();

MusicBoard/Views/UserProfile/Login.cshtml
@model LoginViewModel
@{
    ViewData["Title"] = "Login";
}

@section Styles{
    <link rel="stylesheet" href="~/css/registration.css" />
}
<div class="bigwhitediv" style="width:60%;min-width:400px;" align="left">
    <div id="form-container" class="container-fluid" align="left">
        <form method="post">
            <h2>Аворизация</h2>
            <div asp-validation-summary="ModelOnly"></div>
            <p>
                <label asp-for="Login">Логин</label>
                <input asp-for="Login" class="form-control" type="text">
                <span asp-validation-for="Login"></span>
            </p>
            <p>
                <label asp-for="Password">Пароль</label>
                <input asp-for="Password" class="form-control" type="password">
                <span asp-validation-for="Password"></span>
            </p>
            <input class="btn form-control" type="submit" value="Войти" />
        </form>
    </div>
</div>

MusicBoard/Views/UserProfile/Ratings.cshtml
@using System.Collections
@model RatingsViewModel
@{
    ViewData["Title"] = "Ratings";
}

@section Styles{
    <link rel="stylesheet" href="~/css/userprofile.css">
}
@functions{
    SelectList GetOptions()
    {
        Int32 yearNow = DateTime.Now.Year;
        ArrayList options = new ArrayList { new { value = 0, text = "-" } };
        options.AddRange(Enumerable.Range(1, 10).Select(a => new { value = a, text = a }).ToList());

        return new SelectList(options, "value", "text", Model.RatingConstraint);
    }
}

<div class="bigwhitediv col-lg-7" style="width:80%;">
    <div class="container-fluid" align="left">
        <h5>Альбомы пользователя @Html.ActionLink(Model.UserAnchor.UserName, "UserInfo", "UserProfile", new { nickname = Model.UserAnchor.UserName })</h5>

        <form method="get" asp-action="ratings" class="form-inline"
              asp-route-nickname="@Model.UserAnchor.UserName" asp-route-page="@Model.PageViewModel.PageNumber">
            <label for="rating">с оценкой</label>
            <select name="rating" class="form-control m-2" style="width:100px;height:30px;padding:0 10px;" asp-items="GetOptions()"></select>
            <input type="submit" style="height:30px;padding:0 10px;" class="btn form-control btn-success" value="найти"/>
        </form>
        <table class="table table-striped table-bordered activities-table">
            <tbody>
                @foreach (var album in Model.Ratings)
                {
                    <tr>
                        <td style="width:70px;">
                            @if (album.HasImage)
                            {
                                <img src="~/images/albums/@(album.AlbumId).jpg">

                            }
                            else
                            {
                                <img src="~/images/default.jpg">

                            }

                        </td>
                        <td style="width:50px;">
                            <div class="activity-date">
                                <div class="activity-month">@album.RatingDate.Month</div>
                                <div class="activity-day">@album.RatingDate.Day</div>
                                <div class="activity-year">@album.RatingDate.Year</div>
                            </div>
                        </td>
                        <td style="width:200px;">@album.Rating/10</td>
                        <td style="text-align: left;">
                            <a style="font-weight: bold;" asp-controller="artist"
                               asp-action="artistinfo" asp-route-url="@album.Artist.Url">@album.Artist.Name</a>
                            -
                            <a asp-controller="album" asp-action="albuminfo" asp-route-url="@album.AlbumUrl">@album.AlbumFullName</a>
                            <span style="font-size: 13px;color: gray">(@album.ReleaseYear)</span>
                        </td>
                        <td style="width: 200px">
                            @foreach (var genre in album.Genres)
                            {
                                <p style="margin-bottom:2px;">
                                    <a asp-controller="genre" asp-action="genreinfo" asp-route-id="@genre.GenreId">
                                        @genre.GenreName
                                    </a>
                                </p>
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>

        <page-link page-action="ratings" page-model="Model.PageViewModel" asp-route-nickname="@Model.UserAnchor.UserName">

        </page-link>
    </div>
</div>

MusicBoard/Views/UserProfile/Registration.cshtml
@model UserInfoViewModel
@{
    ViewData["Title"] = "Registration";
}
@section Styles{
    <link rel="stylesheet" href="~/css/registration.css" />
}
    <div class="bigwhitediv" style="width:60%;min-width:400px;" align="left">
        <div id="form-container" class="container-fluid" align="left">
            <form method="post">
                <h2>Регистрация</h2>
                <div asp-validation-summary="ModelOnly"></div>
                <p>
                    <label asp-for="Nickname">Логин</label>
                    <input asp-for="Nickname" class="form-control" type="text">
                    <span asp-validation-for="Nickname"></span>
                </p>
                <p>
                    <label asp-for="Email">E-Mail</label>
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email"></span>
                </p>
                <p>
                    <label asp-for="Password">Пароль</label>
                    <input asp-for="Password" class="form-control">
                    <span asp-validation-for="Password"></span>
                </p>
                <p>
                    <label asp-for="ConfirmPassword">Повторите пароль</label>
                    <input asp-for="ConfirmPassword" class="form-control">
                    <span asp-validation-for="ConfirmPassword"></span>
                </p>
                <br />
                <h3>Расскажите о себе</h3>
                <p>
                    <label asp-for="Name">Имя</label>
                    <input asp-for="Name" type="text" class="form-control" />
                    <span asp-validation-for="Name"></span>
                </p>
                <p>
                    <label asp-for="Surname">Фамилия</label>
                    <input asp-for="Surname" type="text" class="form-control" />
                    <span asp-validation-for="Surname"></span>
                </p>
                <p>
                    <label asp-for="BirthDate">Дата рождения</label>
                    <input asp-for="BirthDate" class="form-control" type="date" />
                    <span asp-validation-for="BirthDate"></span>
                </p>
                <p>
                    <label asp-for="Gender">Пол</label>
                    <select asp-for="Gender" asp-items="Html.GetEnumSelectList<Gender>()" class="form-control"></select>
                </p>
                <p>
                    <label asp-for="About">О себе</label>
                    <textarea asp-for="About" class="form-control" rows="6"></textarea>
                </p>
                <p>
                    <label asp-for="Favourites">Любимые музыканты</label>
                    <textarea asp-for="Favourites" class="form-control" rows="6"></textarea>
                    <span asp-validation-for="Favourites"></span>
                </p>
                <p>
                    <label asp-for="Country">Страна</label>
                    <input asp-for="Country" class="form-control" />
                </p>
                <input type="submit" class="btn btn-primary" value="Регистрация">
            </form>
        </div>
    </div>

@section Scripts
{
    @Html.Partial("_ValidationScriptsPartial")
}

MusicBoard/Views/UserProfile/UserInfo.cshtml
@model UserInfoViewModel
@{
    ViewData["Title"] = "UserProfile";
}
@functions{
    String GetString(Microsoft.AspNetCore.Html.IHtmlContent content)
    {
        var writer = new System.IO.StringWriter();
        content.WriteTo(writer, System.Text.Encodings.Web.HtmlEncoder.Default);
        return writer.ToString();
    }
}
@section Styles{
    <link rel="stylesheet" href="~/css/userprofile.css">
}

<div class="bigwhitediv col-lg-7" style="width:80%;">
    <div class="container-fluid">
        <div class="row">
            <div class="col profile-header justify-content-end">
                <p style="margin-bottom:0">
                    участник с
                    @Model.RegistrationDate.ToString("dd.MM.yyyy"), #@Model.SurrogateId,
                    <span class="profilename">@Model.Nickname</span>
                </p>
            </div>
        </div>
        <div class="row">
            <div class="card">
                <div class="card-header">Профиль пользователя</div>
                @if (!Model.HasImage)
                {
                    <img class="card-img-top" src="~/images/default.jpg" alt="card photo" />
                }
                else
                {
                    <img class="card-img-top" src="~/images/users/@(Model.SurrogateId).jpg" alt="card photo" />

                }
                @if (User.Identity.IsAuthenticated && User.Identity.Name == Model.Nickname)
                {
                    <form asp-action="SetImage" method="post" enctype="multipart/form-data">
                        <input type="file" class="form-control" name="image" value="обзор">
                        <input type="submit" class="form-control" value="загрузить">
                    </form>
                }

                <div class="card-body">
                    <h5 class="card-title">@Model.Name @Model.Surname</h5>
                    <div class="card-text">
                        @(Model.BirthDate.HasValue ? (new DateTime((DateTime.Now - Model.BirthDate.Value).Ticks).Year - 1).ToString() : "-"),
                        @Html.DisplayFor(m => m.Gender),
                        @Model.Country.
                    </div>
                </div>
            </div>
            <div class="col profile-info-container">
                <table class="table table-striped profile-info" style="text-align: left">
                    <tbody>
                        <tr>
                            <td>О себе:</td>
                            <td>@Model.About</td>
                        </tr>
                        <tr>
                            <td>Любимые исполнители:</td>
                            <td>
                                @if (Model.FavouritesLexems?.Length != 0)
                                {
                                    @Model.FavouritesLexems?[0]
                                }
                                @for (Int32 i = 1; i < Model.FavouritesLexems?.Length; i++)
                                {
                                    <a asp-action="artistinfo" asp-controller="artist" asp-route-url="@Model.FavouritesAnchors[i-1].Url">@Model.FavouritesAnchors[i - 1].Name</a>
                                    @Model.FavouritesLexems[i]

                                }
                            </td>
                        </tr>
                    </tbody>
                </table>
                @if (User.Identity.IsAuthenticated && User.Identity.Name == Model.Nickname)
                {
                    <div class="row">
                        <div class="col profile-btn-wrapper bg-lgray">
                            <a class="btn align-right btn-secondary" href="#">Настройки</a>
                            <a class="btn align-right btn-secondary" style="margin-right: 15px" href="#">Друзья</a>
                        </div>
                    </div>
                }

            </div>
        </div>
        @*<div class="row">
            <div class="col">
                <form class="form-inline form-group-sm collection-search-form align-right">
                    <label for="text" style="padding:10px">Поиск в коллекции</label>
                    <input type="text" class="form-control" id="collection-search-key">
                    <label for="text" style="padding:10px">по</label>
                    <select id="search-type" class="form-control">
                        <option value="artist">Исполнитель</option>
                        <option value="album">Релиз</option>
                        <option value="genre">Жанр</option>
                        <option value="year">Год выпуска</option>
                    </select>

                    <button type="submit" style="margin-left:10px;" class="btn btn-success">поиск</button>
                </form>
            </div>
        </div>*@
        <div class="row" id="ratings-wrapper">
            <div class="col collection-navigation">
                <ul class="nav nav-tabs bg-lgray nav-light">
                    <li class="nav-item">
                        <a class="nav-link active" data-toggle="tab" href="#activities">история</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" data-toggle="tab" href="#rating-scale">
                            оценки <span style="color: red">[@Model.RatingsCount]</span>
                        </a>
                    </li>
                </ul>

                <!--Tab panels -->
                <div class="tab-content">
                    <div class="tab-pane active" id="activities">
                        <table class="table table-striped table-bordered activities-table">
                            <tbody>
                                @foreach (var album in Model.Ratings)
                                {
                                    <tr id="tr-first">
                                        <td style="width:70px;">
                                            @if (album.HasImage)
                                            {
                                                <img src="~/images/albums/@(album.AlbumId).jpg">

                                            }
                                            else
                                            {
                                                <img src="~/images/default.jpg">

                                            }

                                        </td>
                                        <td style="width:50px;">
                                            <div class="activity-date">
                                                <div class="activity-month">@album.RatingDate.ToString("MMM")</div>
                                                <div class="activity-day">@album.RatingDate.Day</div>
                                                <div class="activity-year">@album.RatingDate.Year</div>
                                            </div>
                                        </td>
                                        <td style="width:200px;">@album.Rating/10</td>
                                        <td style="text-align: left;">
                                            <a style="font-weight: bold;" asp-controller="artist"
                                               asp-action="artistinfo" asp-route-url="@album.Artist.Url">@album.Artist.Name</a>
                                            -
                                            <a asp-controller="album" asp-action="albuminfo" asp-route-url="@album.AlbumUrl">@album.AlbumFullName</a>
                                            <span style="font-size: 13px;color: gray">(@album.ReleaseYear)</span>
                                        </td>
                                        <td style="width: 200px">
                                            @foreach (var genre in album.Genres)
                                            {
                                            <p style="margin-bottom:2px;">
                                                <a asp-controller="genre" asp-action="genreinfo" asp-route-id="@genre.GenreId">
                                                    @genre.GenreName
                                                </a>
                                            </p>
                                            }
                                        </td>
                                    </tr>

                                }

                                <tr id="tr-last" style="height:30px">
                                    <td>
                                        <a class="activities-expand" asp-action="ratings" 
                                           asp-route-nickname="@Model.Nickname">еще...</a>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <div class="tab-pane" id="rating-scale">
                        <table class="table table-striped table-bordered ratings-table">
                            <thead>
                                <tr>
                                    <td style="width:150px;">Всего оценок:</td>
                                    <td style="width:100px;">
                                        <a style="font-weight: bolder; text-decoration: underline"
                                           asp-action="ratings" asp-route-nickname="@Model.Nickname">@Model.RatingsCount</a></td>
                                    <td />
                                </tr>
                            </thead>
                            @await Component.InvokeAsync("RatingScale", new { nickname = Model.Nickname })
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <br />
    </div>
</div>